
# Every file needs to contain a header, that provides kas with information
# about the context of this file.
header:
  # The `version` entry in the header describes for which configuration
  # format version this file was created. It is used by kas to figure
  # out if it is compatible with this file. The version is an integer that
  # is increased on every format change.
  version: 8
# The machine as it is written into the `local.conf` of bitbake.
machine: qemux86-64

target: core-image-phosh

# The distro name as it is written into the `local.conf` of bitbake.
distro: poky

repos:
  # Include local layer (e.g. conf/layer.conf)
  meta-custom:

  # Here we include a list of layers from the poky repository to add
  # to bblayers.conf:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    refspec: master
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    refspec: master
    layers:
      meta-oe:
      meta-networking:
      meta-python:
      meta-gnome:

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  standard: |
    CONF_VERSION = "2"

  debug-tweaks: |
    EXTRA_IMAGE_FEATURES = "debug-tweaks"

  diskmon: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        ABORT,${TMPDIR},100M,1K \
        ABORT,${DL_DIR},100M,1K \
        ABORT,${SSTATE_DIR},100M,1K \
        ABORT,/tmp,10M,1K"

  distro_features: |
    DISTRO_FEATURES:append = " opengl pam polkit pulseaudio gobject-introspection-data wayland x11"

  systemd_config: |
    DISTRO_FEATURES:append = " systemd"
    VIRTUAL-RUNTIME_init_manager = "systemd"
    DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
    VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
    NETWORK_MANAGER = "systemd"

  default_passcode: |
    # mkpasswd -m sha512crypt
    # make sure to escape $
    INHERIT += "extrausers"
    EXTRA_USERS_PARAMS = "usermod -p '\$6\$HuoBc4fk6RuNTRRN\$AWcXL6LR5XXnWTtqVDTsPlg/GXOC9VpWyfaG6jfLTIbQ0ZbGbspavt7VFj3p/RwSDIdNKuW.haroPlCyktm.0.' phosh;"

  locales: |
    IMAGE_LINGUAS = "en-us"

