- name: Download artifact
  get_url:
    url: "{{ item.url }}"
    dest: "{{ zuul.project.src_dir }}/{{ item.job }}-deploy.tar.zst"
    checksum: "sha1:{{ item.metadata.sha1 }}"
  retries: 3
  delay: 10
  register: result
  until: result is succeeded

- name: Create publish directory
  ansible.builtin.file:
    path: "{{ publish_base_dir }}/{{ item.job }}/"
    mode: "0755"
    state: directory

- name: Publish file
  ansible.builtin.copy:
    src: "{{ zuul.project.src_dir }}/{{ item.job }}-deploy.tar.zst"
    dest: "{{ publish_base_dir }}/{{ item.job }}/{{ item.job }}-deploy.tar.zst"
    remote_src: yes
    unsafe_writes: no

- name: Write checksum file
  ansible.builtin.copy:
    dest: "{{ publish_base_dir }}/{{ item.job }}/{{ item.job }}-deploy.tar.zst.sha1sum"
    content: |
      {{ item.metadata.sha1 }}  {{ item.job }}-deploy.tar.zst
